### ISSUE TITLE
ccucxtocuc typo in pycountry argument

### ISSUE THREAD

**Issue by dspreitz** [acasadoalonso/SWiface#3]
ccucxtocuc contains following code, which does not execute
`        ccc = pycountry.countries.get(alpha2=pil[0])            # convert it to the 3 chars ISO code
        country=ccc.alpha3
`

According to https://pypi.python.org/pypi/pycountry the argument must be changed to alpha_2 and alpha_3 as shown below.

`        ccc = pycountry.countries.get(alpha_2=pil[0])            # convert it to the 3 chars ISO code
        country=ccc.alpha_3
`

**Comment by acasadoalonso** [comment]
Dominic,
Be aware that is different from the version in Pi to the version of Ubuntu.
Fixed now

AC/.

**Comment by acasadoalonso** [comment]
Fixed now
